- platform: mqtt
  name: "Garage Door"
  state_topic: "stat/alarmsensors/STATUS10"
  # {"StatusSNS":{"Time":"2019-10-13T18:53:50","Switch1":"OFF","Switch2":"ON","Switch3":"OFF"}}
  value_template: "{{value_json.StatusSNS.Switch1 }}"
  command_topic: "cmnd/garage/POWER"
  payload_open: "ON"
  payload_close: "OFF"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Single Garage Door"
  state_topic: "stat/alarmsensors/POWER2"
  command_topic: "cmnd/smallgarage/POWER"
  payload_open: "ON"
  payload_close: "OFF"
  payload_stop: "ON"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Patio Door"
  state_topic: "stat/alarmsensors/STATUS10"
  value_template: "{{value_json.StatusSNS.Switch5 }}"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Garage Entrance Door"
  state_topic: "stat/alarmsensors/STATUS10"
  value_template: "{{value_json.StatusSNS.Switch6 }}"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Sensor 8"
  state_topic: "stat/alarmsensors/STATUS10"
  value_template: "{{value_json.StatusSNS.Switch8 }}"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

  #- platform: mqtt
  #name: "A Door"
  #state_topic: "stat/alarmsensors/STATUS10"
  #value_template: "{{value_json.StatusSNS.Switch1 }}"
  #state_open: "OFF"
  #state_closed: "ON"
  #optimistic: false

