- platform: mqtt
  name: "Garage Door"
  state_topic: "tele/alarmsensors/SENSOR"
  value_template: "{{value_json.Switch1 }}"
  command_topic: "cmnd/garage/POWER"
  payload_open: "ON"
  payload_close: "OFF"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Single Garage Door"
  state_topic: "stat/alarmsensors/POWER2"
  command_topic: "cmnd/smallgarage/POWER"
  payload_open: "ON"
  payload_close: "OFF"
  payload_stop: "ON"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Patio Door"
  state_topic: "tele/alarmsensors/SENSOR"
  value_template: "{{value_json.Switch5 }}"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Garage Entrance Door"
  state_topic: "tele/alarmsensors/SENSOR"
  value_template: "{{value_json.Switch6 }}"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false

- platform: mqtt
  name: "Sensor 8"
  state_topic: "tele/alarmsensors/SENSOR"
  value_template: "{{value_json.Switch8 }}"
  state_open: "OFF"
  state_closed: "ON"
  optimistic: false
