title: SmartHouse
theme: dark-mode

views:

  # Home 
  - icon: mdi:home-assistant
    title: Home
    cards:
      - type: glance
        title: Doors
        entities:
          - cover.garage_door
          - cover.single_garage_door
          - cover.patio_door
          - cover.garage_entrance_door

      - type: glance
        title: Outside Conditions
        entities:
          - sensor.outdoor_temperature
          - sensor.outdoor_humidity
          - sensor.forecast_condition

            #- type: picture-entity
            #entity: vacuum.robo_vac_2
            #aspect_ratio: 50%
            #camera_image: camera.deebot_live_map

      - type: glance
        title: Lights
        entities:
          - switch.kitchen_island
          - switch.kitchen_spot_light
          - switch.bar_light
          - switch.office_light
          - switch.living_room_light
          - light.living_room_light

      - type: glance
        title: Media
        entities:
          - media_player.deestv
          - media_player.kitchen_display
          - media_player.kitchen_home
          - media_player.office
          - media_player.bose_soundbar

      - type: entities
        title: Sprinklers
        show_header_toggle: true
        entities:
          - entity: switch.garden_plus_right_back_yard
            name: Garden
          - switch.side_yard
          - switch.right_front_yard
          - switch.front_flower_beds
          - switch.left_front_yard
          - switch.right_back_yard
          - switch.back_yard_left
          - switch.left_middle_back_yard

            #- type: glance
            #icon: mdi:weather-pouring
            #title: Weather
            #entities:
            #- weather.dark_sky
            #- weather.openweathermap

  # Outside
  - title: Outside
    path: Outside
    theme: dark-mode
    cards:
      - type: glance
        title: Outside Plugs
        entities:
          - switch.outdoor_plug
      - type: glance
        title: Outside Conditions
        entities:
          - sensor.outdoor_temperature
          - sensor.outdoor_humidity
          - sensor.forecast_condition

      - type: picture-entity
        entity: camera.weather_radar

  # Weather
  - icon: mdi:weather-pouring
    title: Weather
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: weather-forecast
        entity: weather.openweathermap

